on:
    push:
        branches:
            - master







jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
        - name: 'testing git hub'
          run: pwd
          run: echo eman
          run: ls

        - uses: actions/checkout@v3
          run: ls


      